### PR TITLE
7 add basic UI

### PR DESCRIPTION
**Pull request by mitchellkazin15**
Added menu with simple navigation, ability to start game through the menu, simple HUD, and pause menu.

HUD is just a placeholder. When we have more content in place it will need to be connected to signals from the player

### CODE REVIEW

**Comment by wchaney98** [comment]
Super dope menu. Only issue is I can't get the pause menu to work - can't click any of the buttons. I double checked the process modes, tried deleting my .godot folder and re-importing the project. Not sure what's happening

**Comment by mitchellkazin15** [comment]
> Super dope menu. Only issue is I can't get the pause menu to work - can't click any of the buttons. I double checked the process modes, tried deleting my .godot folder and re-importing the project. Not sure what's happening

Fixed. I broke it when I added the HUD, the mouse filter got set to "stop" instead of ignore or pass, so it was eating the mouse inputs

**Review by wchaney98 — APPROVED** [review]

**Review by TheAdamSmith — APPROVED** [review]
Nice! I think this looks sick. I am surprised at how fast stuff is coming together.

one minor nit, I think I would prefer if the single/multiplayer menu was in the same location as the main menu. Didn't see the second menu at first lol. But feel free to merge and we can  adjust it later

**Comment by mitchellkazin15** [comment]
> Nice! I think this looks sick. I am surprised at how fast stuff is coming together.
> 
> one minor nit, I think I would prefer if the single/multiplayer menu was in the same location as the main menu. Didn't see the second menu at first lol. But feel free to merge and we can adjust it later

Oh I see what you mean, it's pretty small on the left side. I think we'll eventually have more options like "hero select", "map", "difficulty", etc so I think the vertical orientation makes more sense in that case, but for now I can at least make the buttons a little bigger/more visible

**Pull request merged**
